pipeline {
    agent any
    stages {
       stage('Checkout source code') {
            steps {
                git branch: 'dev', url: 'https://github.com/prjpracticeteam/DevOps-Work.git'
            }
        }
        stage('Build Docker image') {
            steps {
                sh 'docker build -t pythonimage:1.0 DevOps-Work/Task-1/.'
            }
        }
        stage('Run Docker container') {
            steps {
                sh 'docker run pythonimage:1.0'
            }
        }
    }
}
